# This error tag corresponds to syslog messages notifying that the configured
# bgp neighbor has changed state
messages:
  # 'error' should be unique and vendor agnostic. Currently we are using the JUNOS syslog message name as the canonical name.
  # This may change if we are able to find a more well defined naming system.
  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
      oldState|bgp_state_convert: (\w+)
      newState|bgp_state_convert: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from {oldState} to {newState} (event {event})'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
        bgp//neighbors//neighbor//{peer}//state//session-state: newState
        bgp//neighbors//neighbor//{peer}//state//session-state-old: oldState
      static: {}
