messages:
  # 'error' should be unique and vendor agnostic. Currently we are using the JUNOS syslog message name as the canonical name.
  # This may change if we are able to find a more well defined naming system.
  - error: BGP_PREFIX_THRESH_EXCEEDED
    tag: BGP_PREFIX_THRESH_EXCEEDED
    values:
      peer: (\d+\.\d+\.\d+\.\d+)
      asn: (\d+)
      limit|int: (\d+)
      current|int: (\d+)
      table: (\w+)
      type: (\w+)
      peeringType: (\w+)
    line: '{peer} ({peeringType} AS {asn}): Configured maximum prefix-limit threshold({limit}) exceeded for {table}-{type} nlri: {current} (instance master)'
    model: openconfig_bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//afi_safis//afi_safi//{table}//state//prefixes//received: current
        bgp//neighbors//neighbor//{peer}//afi_safis//afi_safi//{table}//ipv4_{type}//prefix_limit//state//max_prefixes: limit
      static: {}
  - error: BGP_PREFIX_THRESH_EXCEEDED
    tag: BGP_PREFIX_THRESH_EXCEEDED
    values:
      peer: ([\w\d:]+)
      asn: (\d+)
      limit|int: (\d+)
      current|int: (\d+)
      table: (\w+)
      type: (\w+)
      peeringType: (\w+)
    line: '{peer} ({peeringType} AS {asn}): Configured maximum prefix-limit threshold({limit}) exceeded for {table}-{type} nlri: {current} (instance master)'
    model: openconfig_bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//afi_safis//afi_safi//{table}//state//prefixes//received: current
        bgp//neighbors//neighbor//{peer}//afi_safis//afi_safi//{table}//ipv6_{type}//prefix_limit//state//max_prefixes: limit
      static: {}
